How to find the ways to traverse edges
A1 =
```

0 1 1 0 0 0 0
1 0 0 1 1 1 0
1 0 0 0 0 1 1
0 1 0 0 0 1 1
0 1 0 0 0 0 1
0 1 1 1 0 0 0
0 0 1 1 1 0 0
```

and A2 =

```
0 0 1 1 0 0 1
0 0 1 1 1 0 0
1 1 0 0 0 0 0
1 1 0 0 1 1 1
0 1 0 1 0 0 1
0 0 0 1 0 0 1
1 0 0 1 1 1 0
```

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx

In [8]:
# Adjacency matrix for graph A1
a1 = np.array([[0, 1, 1, 0, 0, 0, 0],
               [1, 0, 0, 1, 1, 1, 0],
               [1, 0, 0, 0, 0, 1, 1],
               [0, 1, 0, 0, 0, 1, 1],
               [0, 1, 0, 0, 0, 0, 1],
               [0, 1, 1, 1, 0, 0, 0],
               [0, 0, 1, 1, 1, 0, 0]])

a2 = np.array([[0,0,1,1,0,0,1],
               [0,0,1,1,1,0,0],
               [1,1,0,0,0,0,0],
               [1,1,0,0,1,1,1],
               [0,1,0,1,0,0,1],
               [0,0,0,1,0,0,1],
               [1,0,0,1,1,1,0]])

print("Original matrix A1:")
print(a1)

a1_2 = np.multiply(a1, a1)
a1_3 = np.multiply(a1, a1_2)

print("Matrix A1^3:")
print(a1_3)

a1_7 = np.linalg.matrix_power(a1, 7)
print("Matrix A1^7:")
print(a1_7)

node_1_onehot = np.array([1, 0, 0, 0, 0, 0, 0])
three_hop_neighbors_from_node_1 = np.matmul(a1_3, node_1_onehot)
print("Three hop neighbors from node 1:")
print(three_hop_neighbors_from_node_1)

hop_7_times_neighbors_from_node_1 = np.matmul(a1_7, node_1_onehot)
print("7 hops neighbors from node 1:")
print(hop_7_times_neighbors_from_node_1)

a2_3 = np.linalg.matrix_power(a2, 3)
a2_7 = np.linalg.matrix_power(a2, 7)

hop_3_neighbours_from_node_1 = np.matmul(a2_3, node_1_onehot)
print("3 hops neighbors from node 1 in A2:")
print(hop_3_neighbours_from_node_1)
hop_7_neighbours_from_node_1 = np.matmul(a2_7, node_1_onehot)
print("7 hops neighbors from node 1 in A2:")
print(hop_7_neighbours_from_node_1)

Original matrix A1:
[[0 1 1 0 0 0 0]
 [1 0 0 1 1 1 0]
 [1 0 0 0 0 1 1]
 [0 1 0 0 0 1 1]
 [0 1 0 0 0 0 1]
 [0 1 1 1 0 0 0]
 [0 0 1 1 1 0 0]]
Matrix A1^3:
[[0 1 1 0 0 0 0]
 [1 0 0 1 1 1 0]
 [1 0 0 0 0 1 1]
 [0 1 0 0 0 1 1]
 [0 1 0 0 0 0 1]
 [0 1 1 1 0 0 0]
 [0 0 1 1 1 0 0]]
Matrix A1^7:
[[112 321 256 247 143 191 186]
 [321 376 317 442 321 442 317]
 [256 317 172 256 186 382 329]
 [247 442 256 298 191 399 382]
 [143 321 186 191 112 247 256]
 [191 442 382 399 247 298 256]
 [186 317 329 382 256 256 172]]
Three hop neighbors from node 1:
[0 1 1 0 0 0 0]
7 hops neighbors from node 1:
[112 321 256 247 143 191 186]
3 hops neighbors from node 1 in A2:
[ 2  3  5 10  4  2  8]
7 hops neighbors from node 1 in A2:
[ 582  573  419 1058  692  495  888]
